# Generated by Django 5.1.3 on 2024-12-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('email', models.EmailField(default='default@gmail.com', max_length=254)),
            ],
        ),
    ]
