# Generated by Django 5.1.3 on 2024-12-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course_code',
            new_name='Course_code',
        ),
    ]
