# Generated by Django 5.1.3 on 2024-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_rename_course_code_student_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stauts',
            field=models.CharField(default='MP', max_length=3),
        ),
    ]
