# Generated by Django 5.1.3 on 2024-12-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_student_stauts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stauts',
            new_name='status',
        ),
    ]
